---
# tasks file for mysql-backups
- name: Copiado de script de mysql-backups
  copy:
    src: mysql_backups.sh
    dest: /usr/local/bin/mysql_backups
    mode: +x

- name: Creacion de directorio para backups de BDs
  file:
    path: /home/backups
    state: directory

- name: Crontab backup job for databases
  cron:
    name: "Crontab mysql backup job for {{ item }} database"
    job: mysql_backups --database "{{ item }}" --path "/home/backups/dbs/{{ item }}" --task dump --remove-old 15
    minute: "0"
    hour: "0"
  loop: "{{ mysql_db_backups }}"
  when: mysql_db_backups is defined
