---
- name: Converge
  hosts: all

  # If testing in Docker cron won't be installed
  pre_tasks:
    - name: Install cron
      become: true
      yum:
        name: cronie
        state: present

  roles:

    - role: ome.postgresql
      postgresql_version: "10"

    - role: ansible-role-postgresql-backup
      postgresql_backup_directory: /backup/postgresql
      postgresql_backup_filename_format: >-
        {{ ansible_hostname }}-%Y%m%d.pgdump{{
          postgresql_backup_compress | ternary('.gz', '')
        }}
