---
- name: Installing python docker modules
  pip:
    name:
      - docker==4.4.4
      - docker-compose
    
- name: Installing loki logging docker plugin
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    alias: loki
    state: enable

- name: Adding host entry for loki endpoint
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} loki"
    state: present

- name: Create loki docker folder
  file:
    path: "{{ loki_installation_path }}"
    state: directory

- name: Gatherig the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check if nginx is installed
  set_fact: 
    nginx_installed: true
  when: "'nginx' in ansible_facts.packages"

- name: Copying Loki config file
  copy:
    src: config/loki-config.yaml
    dest: "{{ loki_installation_path }}/loki-config.yaml"

- name: Copying promtail config file
  template:
    src: promtail-config.yaml.j2
    dest: "{{ loki_installation_path }}/promtail-config.yaml"
  register: promtail_config_file

- name: Copying docker-compose.yaml file
  template:
    src: docker-compose.yaml.j2
    dest: "{{ loki_installation_path }}/docker-compose.yaml"
    mode: '600'
    owner: root
  register: docker_compose_file

- name: Deploying Loki docker container
  docker_compose:
    project_src: "{{ loki_installation_path }}/"
    state: present
  when: docker_compose_file.changed or promtail_config_file.changed
  ignore_errors: "{{ ansible_check_mode }}"