---
- name: Checking if azure-cli is installed
  stat:
    path: /usr/local/bin/kubectl
  register: azure_cli_installed

- name: Installing Azure Cli repo
  apt_repository:
    repo: "deb [arch=amd64 trusted=yes signed-by=/etc/apt/trusted.gpg.d/microsoft.asc] \
      https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
    state: present
    update_cache: true
  when: not azure_cli_installed.stat.exists

- name: Install Azure Cli
  apt:
    name: azure-cli
    state: present
