---
vault_mysql_root_user_pwd: ""
vault_mycnf_file: ""

# TODO estas variables van a ser utilizadas para creacion de usuarios y accesos
# mysql_users:
#   - user: test1
#     dbs:
#       - test1
#   - user: test2
#     dbs:
#       - test1
#       - test2