---
- name: Aplicando cambios para configuraciones con letsencrypt
  block:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400
    changed_when: false

  - name: Ensure dependencies are installed
    apt:
      name:
        - nginx
        - certbot
        - python3-certbot-nginx
      state: present

  - name: Creating base nginx config site for get new cert
    template:
      src: vhost_template_http.j2
      dest:  "/etc/nginx/sites-enabled/{{ item.vhost_name }}.conf"
      backup: False
      force: False
    vars:
      vhost_name: "{{ item.vhost_name }}"
      proxy_pass_host: "{{ item.proxy_pass_host }}"
      proxy_pass_port: "{{ item.proxy_pass_port }}"
      aditional_vhost_names: "{{ item.aditional_vhost_names | default() }}"
      ssl_template: False
    with_items: "{{ vhosts }}"

  - name: Create cert if not exists
    command:
      cmd: certbot certonly --nginx --noninteractive --agree-tos --email "{{ certbot_admin_email }}" -d "{{ item.vhost_name }}"
      creates: /etc/letsencrypt/live/{{ item.vhost_name }}
      warn: false
    with_items: "{{ vhosts }}"

  - name: Creating https vhost config files
    template:
      src: vhost_template_https.j2
      dest:  "/etc/nginx/sites-enabled/{{ item.vhost_name }}.conf"
      backup: False
      force: True
    vars:
      vhost_name: "{{ item.vhost_name }}"
      proxy_pass_host: "{{ item.proxy_pass_host | default('127.0.0.1', true) }}"
      proxy_pass_port: "{{ item.proxy_pass_port | default() }}"
      extra_https_local_root_site_configs: "{{ item.extra_https_local_root_site_configs | default() }}"
      extra_http_local_root_site_configs: "{{ item.extra_http_local_root_site_configs | default() }}"
      aditional_vhost_names: "{{ item.aditional_vhost_names | default() }}"
      ssl_template: True
    with_items: "{{ vhosts }}"
    notify: reload nginx
  when: certbot_admin_email is defined

- name: Aplicando cambios para configuraciones sin letsencrypt
  block:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400
    changed_when: false

  - name: Ensure dependencies are installed
    apt:
      name:
        - nginx
      state: present

  - name: Creating base nginx http config for sites
    template:
      src: vhost_template_http.j2
      dest:  "/etc/nginx/sites-enabled/{{ item.vhost_name }}.conf"
      backup: False
      force: False
    vars:
      vhost_name: "{{ item.vhost_name }}"
      proxy_pass_host: "{{ item.proxy_pass_host | default('127.0.0.1', true) }}"
      proxy_pass_port: "{{ item.proxy_pass_port | default() }}"
      extra_http_local_root_site_configs: "{{ item.extra_http_local_root_site_configs | default() }}"
      aditional_vhost_names: "{{ item.aditional_vhost_names | default() }}"
      ssl_template: false
    with_items: "{{ vhosts }}"
    notify: reload nginx
  when: certbot_admin_email is undefined
